export const GET_ALL_WORKBOOKS =
  'DATA_AUTOMATION/FETCH/ALL/WORKBOOKS';
export const GET_ALL_WORKBOOKS_SUCCESS =
  'DATA_AUTOMATION/FETCH/ALL/WORKBOOKS/SUCCESS';
export const CREATE_WORKBOOK_SUCCESS =
  'DATA_AUTOMATION/CREATE/NEW/WORKBOOK/SUCCESS';
export const CREATE_WORKBOOK = 'DATA_AUTOMATION/CREATE/NEW/WORKBOOK';
